name: Code Style Testing
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.3.0 flake8==4.0.1
      - name: Black Formatting test
        run: black --check . -l 79
      - name: Flake8 Style Testing
        run: flake8 .